DROP TABLE IF EXISTS authors;

CREATE TABLE authors(
author_id INT AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(250) NOT NULL,
last_name VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS books;

CREATE TABLE  books(
id INT AUTO_INCREMENT PRIMARY KEY,
author_id INT,
title VARCHAR(250) NOT NULL,
priceOld  VARCHAR(250) DEFAULT NULL,
price VARCHAR(250) DEFAULT NULL,
CONSTRAINT fk_authorId FOREIGN KEY (id) REFERENCES  authors(author_id)
);